services:
  nginx:
    depends_on:
      - frontend
      - backend
    container_name: nginx-prod
    build:
      target: production
    image: nginx-prod:${VERSION_NGINX}

  frontend:
    depends_on:
      postgres:
        condition: service_healthy
    container_name: front-prod
    build:
      target: production
    image: front-prod:${VERSION_FRONT}
  
  backend:
    depends_on:
      postgres:
        condition: service_healthy
    container_name: back-prod
    build:
      target: production
    image: back-prod:${VERSION_BACK}

  postgres:
    container_name: postgres-prod
    build:
      target: production
    image: postgres-prod:${VERSION_POSTGRES}
    healthcheck:
      test: 'psql -c --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"'
      interval: 10s
      timeout: 3s
      retries: 2
    volumes:
      - postgress-db-volume:/var/lib/postgresql/data

volumes:
  postgress-db-volume:
    name: postgress-prod-volume
    driver: local
